#!/usr/bin/env python
"""
47_full_model.py

Full likelihood and estimation for the three-component generative model
of SARS-CoV-2 spike evolution.

THE MODEL
---------
Three coupled processes, three parameters:

COMPONENT 1: CONSTELLATION BRANCHING  (parameter: mu)
  At each month t, each constellation c in cluster k spawns new
  constellations by adding one mutation drawn from the background
  mutation frequency distribution:

    c' = c union {m}  with probability mu * freq(m)

  The expected fraction of cluster k's sequences in new constellations
  (new_set_share) is determined by mu:

    E[new_set_share_k(t)] = mu * mean_set_size_k(t)

  mu is estimated from the observed monthly turnover rate:
    mu = mean(new_set_share * mean_set_size)^{-1} * turnover_rate

  In practice: mu estimated by matching E[new_set_share] to observed mean.

COMPONENT 2: CLUSTER FREQUENCY DYNAMICS  (parameter: beta)
  Cluster frequencies follow a fitness-weighted update:

    pi_k(t+1) proportional to pi_k(t) * exp(beta * s_k(t))

  where s_k(t) = new_set_share_k(t), generated by Component 1.

  Likelihood: cross-entropy between predicted and observed frequencies.

    L_freq(beta) = sum_t sum_k pi_obs_k(t+1) * log pi_pred_k(t+1; beta)

  beta estimated by Poisson regression: already done, beta = 0.49.

COMPONENT 3: REGIME SWITCH  (parameters: gamma, and winner rule)
  Switch probability at t+1 given current entropy H(pi(t)):

    P(switch at t+1) = gamma * H(pi(t))

  At a switch, the new dominant cluster is:

    winner = argmax_{k != dom} [log_growth_k(t-1 -> t) + log freq_k(t)]

  Likelihood: binary cross-entropy over switch events.

    L_switch(gamma) = sum_t R_t * log(gamma * H_t) +
                      (1-R_t) * log(1 - gamma * H_t)

  gamma estimated by constrained linear regression: gamma = 0.25.
  Winner rule validated: 6/6 correct on known switches.

CONNECTION BETWEEN COMPONENTS
-----------------------------
new_set_share_k(t) connects Component 1 to Component 2:
  - Component 1 generates it (branching rate mu)
  - Component 2 uses it as the fitness signal (coupling beta)

H(pi(t)) connects Component 2 to Component 3:
  - Component 2 generates pi(t) (frequency dynamics)
  - Component 3 uses its entropy (switch timing)

FULL LIKELIHOOD
---------------
L(mu, beta, gamma) = L_branch(mu) + L_freq(beta) + L_switch(gamma)

All three terms factorise -- parameters estimated independently.

WHAT THE MODEL GENERATES
------------------------
Given pi(t) and the observed cluster state at t:

  1. Sample new constellations: each c spawns c' = c union {m} with
     prob mu * freq(m). This generates phi_k(t+1) and new_set_share_k(t).

  2. Update cluster frequencies:
     pi_k(t+1) proportional to pi_k(t) * exp(beta * s_k(t))

  3. Check for switch:
     R_{t+1} ~ Bernoulli(gamma * H(pi(t+1)))
     If switch: new_dom = argmax_k [log_growth_k + log freq_k(t+1)]

  4. Sample constellation counts:
     For each cluster k: draw n_k sequences, each from phi_k(t+1)

This generates a full {constellation: count} dict -- the observed data object.

EVALUATION
----------
Three separate evaluations, one per component:

  A. mu: does E[new_set_share] match observed? (moment matching)
  B. beta: Spearman(pi_pred(t+1), pi_obs(t+1)) vs copy-forward
  C. gamma: AUC of P(switch) vs observed, walk-forward

Winner rule evaluated separately: recall and precision on 6 switches.

Usage
-----
  python scripts/47_full_model.py
  python scripts/47_full_model.py --estimate  # reestimate all parameters
"""

import argparse
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]

SWITCH_MONTHS = {
    "2021-01": 18, "2021-06": 15, "2022-01": 72,
    "2022-03": 150, "2022-06": 160, "2023-02": 107,
}


def log(m):
    print(m, flush=True)


def entropy(p):
    p = np.asarray(p); p = p[p > 0]
    return float(-(p * np.log(p)).sum())


def spearman(a, b):
    from scipy.stats import rankdata
    ar, br = rankdata(a), rankdata(b)
    if ar.std() < 1e-12 or br.std() < 1e-12: return np.nan
    return float(np.corrcoef(ar, br)[0, 1])


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--csv", default=str(ROOT / "outputs" / "40_internal.csv"))
    ap.add_argument("--estimate", action="store_true",
                    help="reestimate all parameters from data")
    ap.add_argument("--beta", type=float, default=0.49)
    ap.add_argument("--gamma", type=float, default=0.25)
    ap.add_argument("--out", default=str(ROOT / "outputs" / "47_full_model.csv"))
    args = ap.parse_args()

    df = pd.read_csv(args.csv)
    months = sorted(df.month.unique())
    midx = {m: i for i, m in enumerate(months)}
    log(f"{len(df)} cluster-months, {df.cluster.nunique()} clusters, "
        f"{len(months)} months\n")

    # ---- COMPONENT 1: estimate mu from moment matching ----
    log("=" * 74)
    log("COMPONENT 1: BRANCHING (mu)")
    log("=" * 74)
    # E[new_set_share_k(t)] = mu * mean_set_size_k(t)
    # => mu = mean(new_set_share / mean_size) across all cluster-months
    df_valid = df[(df.new_set_share > 0) & (df.mean_size > 0)].copy()
    mu = float(df_valid.new_set_share.mean() / df_valid.mean_size.mean())
    log(f"  mu = mean(new_set_share / mean_size) = {mu:.4f}")
    log(f"  interpretation: each position mutates with prob {mu:.4f} per month")
    log(f"  implied monthly turnover: mu * mean_size = "
        f"{mu * df.mean_size.mean():.3f} new mutations per sequence per month")
    log(f"  observed mean new_set_share: {df.new_set_share.mean():.3f}")
    log(f"  predicted mean new_set_share: {mu * df.mean_size.mean():.3f}")

    # ---- COMPONENT 2: estimate/evaluate beta ----
    log("\n" + "=" * 74)
    log("COMPONENT 2: FREQUENCY DYNAMICS (beta)")
    log("=" * 74)

    if args.estimate and "g_next" in df.columns:
        from sklearn.linear_model import PoissonRegressor
        d2 = df.dropna(subset=["new_set_share", "g_next"])
        pm = PoissonRegressor(max_iter=500)
        pm.fit(d2[["new_set_share"]].values, np.exp(d2.g_next.values))
        beta = float(pm.coef_[0])
        log(f"  beta estimated from data: {beta:.4f}")
    else:
        beta = args.beta
        log(f"  beta = {beta} (pre-estimated, script 41)")

    # one-step-ahead evaluation
    state = {}
    for mo in months:
        t = df[df.month == mo]
        if len(t) < 2: continue
        tot = t.freq.sum()
        pi = dict(zip(t.cluster.astype(int), t.freq / tot))
        nss = dict(zip(t.cluster.astype(int), t.new_set_share))
        state[mo] = dict(pi=pi, nss=nss, H=entropy(list(pi.values())),
                         dom=max(pi, key=pi.get))

    usable = [m for m in months if m in state]
    sp_model_list, sp_cf_list = [], []
    for i, mo in enumerate(usable[:-1]):
        mo1 = usable[i + 1]
        st, st1 = state[mo], state[mo1]
        clusters = list(st["pi"].keys())
        pi0 = np.array([st["pi"].get(k, 0.0) for k in clusters])
        nss0 = np.array([st["nss"].get(k, 0.0) for k in clusters])
        pi1_obs = np.array([st1["pi"].get(k, 0.0) for k in clusters])
        f = pi0 * np.exp(beta * nss0)
        pi1_pred = f / f.sum() if f.sum() > 0 else pi0
        sp_model_list.append(spearman(pi1_pred, pi1_obs))
        sp_cf_list.append(spearman(pi0, pi1_obs))

    log(f"  one-step-ahead Spearman: model {np.mean(sp_model_list):.3f}  "
        f"copy-forward {np.mean(sp_cf_list):.3f}  "
        f"gain {np.mean(sp_model_list)-np.mean(sp_cf_list):+.3f}")
    log(f"  beats copy-forward in "
        f"{sum(m>c for m,c in zip(sp_model_list,sp_cf_list))}/{len(sp_model_list)} months")

    # ---- COMPONENT 3: estimate/evaluate gamma + winner rule ----
    log("\n" + "=" * 74)
    log("COMPONENT 3: REGIME SWITCHES (gamma + winner rule)")
    log("=" * 74)

    # compute entropy and switch indicators
    sw_rows = []
    for i, mo in enumerate(usable[:-1]):
        mo1 = usable[i + 1]
        H = state[mo]["H"]
        is_sw = mo1 in SWITCH_MONTHS
        sw_rows.append(dict(month=mo, H=H, is_switch=is_sw))
    sw_df = pd.DataFrame(sw_rows)

    if args.estimate:
        X = sw_df[["H"]].values
        y = sw_df.is_switch.astype(float).values
        b, *_ = np.linalg.lstsq(X, y, rcond=None)
        gamma = max(0.0, float(b[0]))
        log(f"  gamma estimated from data: {gamma:.4f}")
    else:
        gamma = args.gamma
        log(f"  gamma = {gamma} (pre-estimated)")

    sw_df["p_switch"] = (gamma * sw_df.H).clip(0, 1)
    from sklearn.metrics import roc_auc_score
    auc = roc_auc_score(sw_df.is_switch.astype(int), sw_df.p_switch)
    log(f"  switch AUC (in-sample): {auc:.3f}")

    # walk-forward switch AUC
    wf_aucs = []
    for i, mo in enumerate(usable[:-1]):
        if i < 10: continue
        train = sw_df[sw_df.month < mo]
        if train.is_switch.sum() < 1: continue
        b_wf, *_ = np.linalg.lstsq(train[["H"]].values,
                                    train.is_switch.astype(float).values,
                                    rcond=None)
        g_wf = max(0.0, float(b_wf[0]))
        mo1 = usable[i + 1]
        H_t = state[mo]["H"]
        p_sw = float(np.clip(g_wf * H_t, 0, 1))
        is_sw = int(mo1 in SWITCH_MONTHS)
        wf_aucs.append((p_sw, is_sw))

    if len(wf_aucs) > 5:
        ps, ys = zip(*wf_aucs)
        if len(set(ys)) > 1:
            auc_wf = roc_auc_score(list(ys), list(ps))
            log(f"  switch AUC (walk-forward): {auc_wf:.3f}")

    # winner rule: 6/6 validation
    log(f"\n  WINNER RULE: argmax_k [log_growth_k + log_freq_k]")
    correct = 0
    for sw_mo, true_k in SWITCH_MONTHS.items():
        sw_i = midx.get(sw_mo)
        if sw_i is None or sw_i < 2: continue
        mo_prev, mo_curr = months[sw_i-2], months[sw_i-1]
        t_prev = df[df.month==mo_prev].set_index("cluster")
        t_curr = df[df.month==mo_curr].set_index("cluster")
        common = t_prev.index.intersection(t_curr.index)
        dom = t_curr.freq.idxmax()
        scores = {}
        for k in common:
            if k == dom: continue
            f0 = t_prev.loc[k, "freq"]; f1 = t_curr.loc[k, "freq"]
            if f0 > 0 and f1 > 0:
                scores[k] = np.log(f1/f0) + np.log(f1 + 1e-6)
        if not scores: continue
        pred = max(scores, key=scores.get)
        c = pred == true_k
        correct += c
        log(f"  {sw_mo}: pred={pred} true={true_k} {'OK' if c else 'MISS'}")
    log(f"  winner recall: {correct}/6 = {correct/6:.0%}")

    # ---- FULL LIKELIHOOD ----
    log("\n" + "=" * 74)
    log("FULL LOG-LIKELIHOOD  L = L_branch + L_freq + L_switch")
    log("=" * 74)

    # L_branch: Gaussian on new_set_share vs mu * mean_size
    resid = df_valid.new_set_share - mu * df_valid.mean_size
    L_branch = float(-0.5 * (resid**2 / resid.var()).sum())
    log(f"  L_branch(mu={mu:.4f}):   {L_branch:.1f}")

    # L_freq: cross-entropy between predicted and observed cluster frequencies
    L_freq = 0.0
    for i, mo in enumerate(usable[:-1]):
        mo1 = usable[i+1]
        st, st1 = state[mo], state[mo1]
        clusters = list(st["pi"].keys())
        pi0 = np.array([st["pi"].get(k, 0.0) for k in clusters])
        nss0 = np.array([st["nss"].get(k, 0.0) for k in clusters])
        pi1_obs = np.array([st1["pi"].get(k, 0.0) for k in clusters])
        f = pi0 * np.exp(beta * nss0)
        pi1_pred = f / f.sum() if f.sum() > 0 else pi0
        L_freq += float((pi1_obs * np.log(pi1_pred + 1e-12)).sum())
    log(f"  L_freq(beta={beta:.2f}):    {L_freq:.1f}")

    # L_switch: binary cross-entropy
    p = (gamma * sw_df.H).clip(1e-6, 1-1e-6)
    y = sw_df.is_switch.astype(float)
    L_switch = float((y * np.log(p) + (1-y) * np.log(1-p)).sum())
    log(f"  L_switch(gamma={gamma:.3f}): {L_switch:.1f}")
    log(f"  L_total:                 {L_branch+L_freq+L_switch:.1f}")

    # ---- SUMMARY ----
    log("\n" + "-" * 74)
    log("SUMMARY")
    log("-" * 74)
    log(f"  Three parameters, three components, all from sequence counts:")
    log(f"")
    log(f"  mu    = {mu:.4f}  mutation rate per position per month")
    log(f"           estimated from moment matching on new_set_share")
    log(f"           generates: phi_k(t), new_set_share_k(t)")
    log(f"")
    log(f"  beta  = {beta:.4f}  fitness coupling")
    log(f"           estimated by Poisson regression, 575 cluster-months")
    log(f"           generates: pi_k(t+1) from pi_k(t) and new_set_share")
    log(f"           validation: Spearman gain +{np.mean(sp_model_list)-np.mean(sp_cf_list):.3f} over copy-forward")
    log(f"")
    log(f"  gamma = {gamma:.4f}  switch rate per unit entropy")
    log(f"           estimated by linear regression, 35 months, 6 switches")
    log(f"           generates: R_t (switch indicator)")
    log(f"           validation: AUC {auc:.3f} in-sample, {auc_wf:.3f} walk-forward")
    log(f"")
    log(f"  winner rule (no free parameters):")
    log(f"           argmax_k [log_growth_k + log_freq_k] among non-dominant clusters")
    log(f"           validation: {correct}/6 switches correct")
    log(f"")
    log(f"  The model generates:")
    log(f"  - constellation counts within each cluster (via mu and phi_k)")
    log(f"  - cluster frequency distribution (via beta and new_set_share)")
    log(f"  - switch timing and winner (via gamma, H, and winner rule)")

    # save
    out_rows = []
    for i, mo in enumerate(usable[:-1]):
        mo1 = usable[i+1]
        st, st1 = state[mo], state[mo1]
        clusters = list(st["pi"].keys())
        pi0 = np.array([st["pi"].get(k, 0.0) for k in clusters])
        nss0 = np.array([st["nss"].get(k, 0.0) for k in clusters])
        pi1_obs = np.array([st1["pi"].get(k, 0.0) for k in clusters])
        f = pi0 * np.exp(beta * nss0)
        pi1_pred = f / f.sum() if f.sum() > 0 else pi0
        p_sw = float(np.clip(gamma * st["H"], 0, 1))
        out_rows.append(dict(
            month_t=mo, month_t1=mo1,
            H=st["H"], p_switch=p_sw,
            is_switch=mo1 in SWITCH_MONTHS,
            sp_model=spearman(pi1_pred, pi1_obs),
            sp_cf=spearman(pi0, pi1_obs),
        ))

    pd.DataFrame(out_rows).to_csv(args.out, index=False)
    log(f"\n  wrote {args.out}")


if __name__ == "__main__":
    main()
